# =============================================================================
# Secret for Search API Sensitive Configuration
# =============================================================================
# This Secret contains sensitive configuration data for the FastAPI search 
# service. Values are base64 encoded.
#
# To encode values:
#   echo -n "your-secret-value" | base64
#
# To decode values:
#   echo "encoded-value" | base64 --decode
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: pipeline-api-secrets
  namespace: pipeline
  labels:
    app: pipeline-api
    component: secret
type: Opaque
data:
  # API Authentication (base64 encoded)
  API_KEY: "eW91ci1hcGkta2V5LWhlcmU="  # Replace with actual API key
  API_USERNAME: "YWRtaW4="  # Replace with actual username
  API_PASSWORD: "cGFzc3dvcmQ="  # Replace with actual password
  
  # AWS Credentials (base64 encoded)
  AWS_ACCESS_KEY_ID: "WU9VUl9BV1NfS0VZX0lE"  # Replace with actual AWS key
  AWS_SECRET_ACCESS_KEY: "WU9VUl9BV1NfU0VDUkVUX0tFWQ=="  # Replace with actual AWS secret
  
  # Qdrant Authentication (base64 encoded)
  QDRANT_KEY: "eW91ci1xZHJhbnQta2V5LWhlcmU="  # Replace with actual Qdrant key
  
  # AWS Batch Configuration (base64 encoded)
  BATCH_JOB_QUEUE: "cGlwZWxpbmUtam9iLXF1ZXVl"  # Replace with actual job queue
  BATCH_JOB_DEFINITION: "cGlwZWxpbmUtam9iLWRlZmluaXRpb24="  # Replace with actual job definition

---
# =============================================================================
# Registry Secret for Private Container Registry
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: pipeline
  labels:
    app: pipeline-api
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ewogICJhdXRocyI6IHsKICAgICJ5b3VyLXJlZ2lzdHJ5LmNvbSI6IHsKICAgICAgInVzZXJuYW1lIjogInlvdXItdXNlcm5hbWUiLAogICAgICAicGFzc3dvcmQiOiAieW91ci1wYXNzd29yZCIsCiAgICAgICJhdXRoIjogImJhc2U2NC1lbmNvZGVkLXVzZXJuYW1lOnBhc3N3b3JkIgogICAgfQogIH0KfQ==

---
# =============================================================================
# TLS Secret for HTTPS (Optional)
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: pipeline-api-tls
  namespace: pipeline
  labels:
    app: pipeline-api
    component: tls
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLiBbWW91ciBUTFMgY2VydGlmaWNhdGUgaGVyZV0gLi4uCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLiBbWW91ciBUTFMgcHJpdmF0ZSBrZXkgaGVyZV0gLi4uCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
