apiVersion: apps/v1
kind: Deployment
metadata:
  name: oriane-search-api
  labels:
    app: oriane-search-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oriane-search-api
  template:
    metadata:
      labels:
        app: oriane-search-api
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
        - name: api
          image: <aws_account_id>.dkr.ecr.<your-region>.amazonaws.com/oriane-search-api-v1:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
