services:
  qdrant:
    image: qdrant/qdrant:v1.14.1
    restart: unless-stopped
    ports:
      - "6333:6333" # REST
      - "6334:6334" # gRPC
    volumes:
      - /qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__API_KEY: "${QDRANT_API_KEY}"
      QDRANT__STORAGE__SNAPshots_PATH: "/qdrant/storage/snapshots"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - qdrant

volumes:
  qdrant_data:
